version: "3.9"

volumes:
  pgdata:
    driver: local

services:

  db:
    image: postgres
    container_name: rentx_pg
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=rentx
      - POSTGRES_PASSWORD=rentx!@
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: rentx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - "db"