version: "3.9"

volumes:
  pgdata:
    driver: local

services:

  db:
    image: postgres
    container_name: rentx_pg
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - pgdata:/data/postgres

  queue:
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:6379"
